# **Лабораторная работа №1**

## **Выполнил:** Ибрагимов Роман Рифхатович

## **Вариант:** 1

## **Группа:** М8О-303Б-22

# 1. Numpy

Необходимо использовать функции и методы библиотеки numpy. Использовать циклы, генераторы списков **запрещено**.

In [220]:
import numpy as np

1. Создайте матрицу $3 × 3 $ со значениями от 0 до 8.

In [221]:
matrix = np.arange(0, 9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


2. Создайте матрицу шахматной доски  $8 × 8 $, заполненную 'B' и 'W', используя функцию tile.

In [222]:
chessboard = np.tile([['B', 'W'], ['W', 'B']], (4, 4))
print(chessboard)

[['B' 'W' 'B' 'W' 'B' 'W' 'B' 'W']
 ['W' 'B' 'W' 'B' 'W' 'B' 'W' 'B']
 ['B' 'W' 'B' 'W' 'B' 'W' 'B' 'W']
 ['W' 'B' 'W' 'B' 'W' 'B' 'W' 'B']
 ['B' 'W' 'B' 'W' 'B' 'W' 'B' 'W']
 ['W' 'B' 'W' 'B' 'W' 'B' 'W' 'B']
 ['B' 'W' 'B' 'W' 'B' 'W' 'B' 'W']
 ['W' 'B' 'W' 'B' 'W' 'B' 'W' 'B']]


3. Найти индексы ненулевых элементов в произвольном массиве, например: $ [1,2,0,0,4,0,0,4,6,4,0] $


In [223]:
arr = np.array([1, 2, 0, 0, 4, 0, 0, 4, 6, 4, 0])
print(np.nonzero(arr))

(array([0, 1, 4, 7, 8, 9]),)


4. Создайте двумерный массив с единицами на границах и нулями внутри, например:

$ 1 1 1 1 1 $

$ 1 0 0 0 1 $

$ 1 0 0 0 1 $

$ 1 1 1 1 1 $


In [224]:
matrix = np.ones((6, 10), dtype=int)
matrix[1:-1, 1:-1] = 0
print(matrix)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


5. Создайте случайный вектор размером 15 и замените максимальное значение на $NaN$.


In [225]:
vec = np.random.rand(15)
print(f'Изначальный вектор: {vec}')
vec[vec.argmax()] = np.nan
print(f'Изменённый вектор: {vec}')

Изначальный вектор: [0.34161653 0.32625719 0.33010285 0.99200045 0.08332697 0.13841289
 0.77321418 0.389252   0.06735647 0.90462936 0.00913044 0.37208365
 0.47319436 0.47575769 0.41664371]
Изменённый вектор: [0.34161653 0.32625719 0.33010285        nan 0.08332697 0.13841289
 0.77321418 0.389252   0.06735647 0.90462936 0.00913044 0.37208365
 0.47319436 0.47575769 0.41664371]


6. Рассмотрим массив размерности $(6, 7, 8)$. Каков индекс $(i,j,k)$ 100-го элемента?

In [226]:
print(np.unravel_index(99, (6, 7, 8)))
matrix = np.arange(0, 336).reshape(6, 7, 8)
print(matrix) # дополнительная визуализация

(1, 5, 3)
[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 2

7. Рассмотрим случайную матрицу  $15 × 2 $, представляющую декартовы координаты, преобразуйте их в полярные координаты.

In [227]:
cartesian_coords = np.random.rand(15, 2)
print(f'Декартовы координаты:\n {cartesian_coords}')

X = cartesian_coords[:, 0]
Y = cartesian_coords[:, 1]

R = np.sqrt(X ** 2 + Y ** 2)
Phi = np.arctan2(Y, X)

polar_coords = np.column_stack((R, Phi))
print(f'Полярные координаты:\n {polar_coords}')

Декартовы координаты:
 [[0.94826182 0.52789592]
 [0.99656862 0.61641703]
 [0.80912059 0.95187503]
 [0.52334515 0.14896783]
 [0.21058236 0.83095383]
 [0.69953817 0.26544716]
 [0.78450254 0.84573357]
 [0.24356893 0.91667256]
 [0.02656073 0.00380067]
 [0.97344093 0.99492064]
 [0.20234347 0.64607693]
 [0.4579524  0.10654741]
 [0.06918937 0.97637712]
 [0.05522285 0.5557438 ]
 [0.34309163 0.89025301]]
Полярные координаты:
 [[1.08529931 0.50797145]
 [1.17180159 0.55394005]
 [1.24929668 0.86628591]
 [0.54413377 0.27731124]
 [0.85722179 1.32259913]
 [0.74820843 0.36267558]
 [1.15356383 0.82294012]
 [0.94848005 1.31108744]
 [0.02683128 0.14212886]
 [1.39192468 0.79631021]
 [0.67702163 1.2672849 ]
 [0.47018374 0.2285937 ]
 [0.97882555 1.50005122]
 [0.55848074 1.47175398]
 [0.95407666 1.20295079]]


8. По двум массивам $x$ и $y$ постройте матрицу Коши $C$
 $(C_{ij} =\frac{1}{x_i - y_j})$

In [228]:
x = np.random.randint(0, 10, size=6)
y = np.random.randint(-10, -1, size=6)
print(f'x: {x}\ny: {y}')

Cauchy = 1 / (x.reshape((6, 1)) - y)
print(f'Cauchy: {Cauchy}')

x: [2 4 2 7 7 8]
y: [-3 -2 -4 -9 -2 -5]
Cauchy: [[0.2        0.25       0.16666667 0.09090909 0.25       0.14285714]
 [0.14285714 0.16666667 0.125      0.07692308 0.16666667 0.11111111]
 [0.2        0.25       0.16666667 0.09090909 0.25       0.14285714]
 [0.1        0.11111111 0.09090909 0.0625     0.11111111 0.08333333]
 [0.1        0.11111111 0.09090909 0.0625     0.11111111 0.08333333]
 [0.09090909 0.1        0.08333333 0.05882353 0.1        0.07692308]]


9. Рассмотрим матрицу $10 × 3 $, извлеките строки с неравными значениями (например, $[2,2,3]$).

In [229]:
matrix = np.random.randint(1, 3, size=(10, 3))
print(f'Изначальная матрица:\n {matrix}\n')
matrix = matrix[np.any(matrix != matrix[:, [0]], axis=1)]
print(f'Строки с неравными значениями:\n {matrix}')


Изначальная матрица:
 [[1 1 2]
 [2 2 2]
 [1 1 2]
 [2 2 1]
 [2 1 1]
 [1 2 2]
 [1 1 1]
 [1 1 1]
 [2 1 2]
 [1 2 2]]

Строки с неравными значениями:
 [[1 1 2]
 [1 1 2]
 [2 2 1]
 [2 1 1]
 [1 2 2]
 [2 1 2]
 [1 2 2]]


10. Извлеките уникальные строки из двумерного массива.


In [230]:
matrix = np.array([[1, 2, 3, 4], [4, 5, 6, 4], [1, 2, 3, 4], [1, 7, 3, 4], [1, 9, 8, 4], [1, 2, 3, 4]])
unique_string = np.unique(matrix, axis=0)
print(unique_string)

[[1 2 3 4]
 [1 7 3 4]
 [1 9 8 4]
 [4 5 6 4]]


# 2. Pandas

# Найдите ответы на вопросы с помощью предложенного датасета:

Файл с датасетом - `olympics_dataset.csv`

In [231]:
import pandas as pd

In [232]:
# Load dataset here
df = pd.read_csv('olympics_dataset.csv')
df.head()

player_id                   Name Sex            Team  NOC  Year  Season  \
0          0              A Dijiang   M           China  CHN  1992  Summer   
1          1               A Lamusi   M           China  CHN  2012  Summer   
2          2            Gunnar Aaby   M         Denmark  DEN  1920  Summer   
3          3            Edgar Aabye   M  Denmark/Sweden  DEN  1900  Summer   
4         26  Cornelia (-strannood)   F     Netherlands  NED  1932  Summer   

          City       Sport                         Event     Medal  
0    Barcelona  Basketball   Basketball Men's Basketball  No medal  
1       London        Judo  Judo Men's Extra-Lightweight  No medal  
2    Antwerpen    Football       Football Men's Football  No medal  
3        Paris  Tug-Of-War   Tug-Of-War Men's Tug-Of-War      Gold  
4  Los Angeles   Athletics  Athletics Women's 100 metres  No medal

In [233]:
print(df.shape)

(252565, 11)


In [234]:
print(df.columns)

Index(['player_id', 'Name', 'Sex', 'Team', 'NOC', 'Year', 'Season', 'City',
       'Sport', 'Event', 'Medal'],
      dtype='object')


In [235]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252565 entries, 0 to 252564
Data columns (total 11 columns):
 #   Column     Non-Null Count   Dtype 
---  ------     --------------   ----- 
 0   player_id  252565 non-null  int64 
 1   Name       252565 non-null  object
 2   Sex        252565 non-null  object
 3   Team       252565 non-null  object
 4   NOC        252565 non-null  object
 5   Year       252565 non-null  int64 
 6   Season     252565 non-null  object
 7   City       252565 non-null  object
 8   Sport      252565 non-null  object
 9   Event      252565 non-null  object
 10  Medal      252565 non-null  object
dtypes: int64(2), object(9)
memory usage: 21.2+ MB
None


In [236]:
df.drop_duplicates()

player_id                   Name Sex               Team  NOC  Year  \
0               0              A Dijiang   M              China  CHN  1992   
1               1               A Lamusi   M              China  CHN  2012   
2               2            Gunnar Aaby   M            Denmark  DEN  1920   
3               3            Edgar Aabye   M     Denmark/Sweden  DEN  1900   
4              26  Cornelia (-strannood)   F        Netherlands  NED  1932   
...           ...                    ...  ..                ...  ...   ...   
252560    4986655             Sefora Ada   F  Equatorial Guinea  GEQ  2024   
252561    9460001        Emanuela Liuzzi   F              Italy  ITA  2024   
252562    1972077           Isayah Boers   M        Netherlands  NED  2024   
252563    1899865            Kevin Staut   M             France  FRA  2024   
252564    1924402        Charlie Carvell   M      Great Britain  GBR  2024   

        Season         City       Sport                         Event  \
0       Summer    Barcelona  Basketball   Basketball Men's Basketball   
1       Summer       London        Judo  Judo Men's Extra-Lightweight   
2       Summer    Antwerpen    Football       Football Men's Football   
3       Summer        Paris  Tug-Of-War   Tug-Of-War Men's Tug-Of-War   
4       Summer  Los Angeles   Athletics  Athletics Women's 100 metres   
...        ...          ...         ...                           ...   
252560  Summer        Paris   Athletics                  Women's 100m   
252561  Summer        Paris   Wrestling        Women's Freestyle 50kg   
252562  Summer        Paris   Athletics          4 x 400m Relay Mixed   
252563  Summer        Paris  Equestrian                  Jumping Team   
252564  Summer        Paris   Athletics          Men's 4 x 400m Relay   

           Medal  
0       No medal  
1       No medal  
2       No medal  
3           Gold  
4       No medal  
...          ...  
252560  No medal  
252561  No medal  
252562      Gold  
252563    Bronze  
252564    Bronze  

[252565 rows x 11 columns]

In [237]:
df['player_id'].unique().size

235903

In [238]:
df['Name'].unique().size

129992

1. Сколько спортсменов участвовали в Летних Олимпийских играх за всё время?

In [239]:
summer_athlets = df[df['Season'] == 'Summer']

# спортсменов отличаем по именам
print(summer_athlets['Name'].nunique())

129992


2. Найдите участника с наибольшим количеством медалей

In [240]:
medalists = df[df['Medal'] != 'No medal']
medals_cnt = medalists.groupby('Name').size()
print(medals_cnt.idxmax())

Michael Ii


3. Какой спорт является самым популярным, то есть в нём участвовало больше всего спортсменов за всё время?

In [241]:
sports_participation = df.groupby('Sport')['Name'].nunique()
print(sports_participation.idxmax())

Athletics


4. Кто был победителем медального зачёта в 2004 году?

In [242]:
medals_2004 = df[(df['Year'] == 2004) & (df['Medal'] != 'No medal')].groupby('Team')['Medal'].size()
print(medals_2004.idxmax())

United States


5. В каком виде спорта США завоевало наибольшее число медалей?

In [243]:
sport_medals_USA = df[(df['NOC'] == 'USA') & (df['Medal'] != 'No medal')].groupby('Sport')['Medal'].size()
print(sport_medals_USA.idxmax())

Swimming


# С помощью графика покажите:

In [244]:
import plotly.express as px

df = df[df['Season'] == 'Summer'] # да, уже понятно, что весь датасет состоит только из записей о летних играх, но в общем случае правильно проверить

6. Сколько женщин и мужчин участвовало в Летних Олимпийских играх каждый год?

In [245]:
genders_cnt_per_year = df.groupby(['Year', 'Sex']).size().reset_index(name='Count')

figure = px.line(
    genders_cnt_per_year,
    x='Year',
    y='Count',
    color='Sex',
    title='Количество мужчин и женщин, участвовавших в Летних Олимпийских играх каждый год',
    labels={'Year': 'Год', 'Count': 'Количество участников', 'Sex': 'Пол'}
)

figure.update_layout(
    xaxis=dict(
        tickmode='array',
        tickvals=genders_cnt_per_year['Year'].unique()
    )
)

figure.show()

7. Какие 10 стран на текущий момент имеют наибольшее количество золотых медалей?


In [246]:
gold_medals_by_countries = df[df['Medal'] == 'Gold'].groupby('NOC').size().reset_index(name='Count')
top_10_countries = gold_medals_by_countries.sort_values(by='Count', ascending=False).head(10)

figure = px.bar(
    top_10_countries,
    x='NOC',
    y='Count',
    title='Топ 10 стран, имеющие наибольшее количество медалей',
    labels={'NOC': 'Страна', 'Count': 'Количество золотых медалей'}
)

figure.show()

8. Сколько золотых, серебряных и бронзовых медалей зарабатывал СССР отдельно по каждым играм?

In [247]:
ussr_medals = df[(df['NOC'] == 'URS') & (df['Medal'] != 'No medal')]
ussr_medals_per_games = ussr_medals.groupby(['Year', 'Medal']).size().reset_index(name='Count')

medal_order = ['Gold', 'Silver', 'Bronze']
medal_colors = {
    'Gold': '#FFD700',
    'Silver': '#C0C0C0',
    'Bronze': '#CD7F32'
}

figure = px.bar(
    ussr_medals_per_games,
    x='Year',
    y='Count',
    color='Medal',
    title='Количество золотых, серебряных и бронзовых медалей СССР по каждым играм',
    labels={'Year': 'Год', 'Medal_Count': 'Количество медалей', 'Medal': 'Тип медали'},
    category_orders={
        'Medal': medal_order,
        'Year': sorted(ussr_medals_per_games['Year'].unique())
    },
    color_discrete_map=medal_colors,
    barmode='group'
)

figure.update_layout(
    xaxis=dict(
        tickmode='array',
        tickvals=ussr_medals_per_games['Year'].unique()
    )
)

figure.show()

9. Сколько медалей завоёвывали спортсмены и спортсменки (отдельно) команды Китая на каждой олимпиаде?


In [248]:
china_medals = df[(df['NOC'] == 'CHN') & (df['Medal'] != 'No medal')]
china_medals_by_gender = china_medals.groupby(['Year', 'Sex']).size().reset_index(name='Count')

figure = px.bar(
    china_medals_by_gender,
    x='Year',
    y='Count',
    color='Sex',
    title='Количество медалей завоёванных спортсменами и спортсменками команды Китая',
    labels={'Year': 'Год', 'Count': 'Количество медалей', 'Sex': 'Пол'},
    barmode='group'
)

figure.show()

10. Какие 10 стран имеют наибольшее количество участников, не получивших никаких медалей ни на одной из Летних олимпиад?

In [249]:
no_medals = df[df['Medal'] == 'No medal']

no_medals_count = no_medals.groupby('NOC')['Name'].nunique().reset_index(name='Count')

top_10_no_medals = no_medals_count.sort_values(by='Count', ascending=False).head(10)

fig = px.bar(
    top_10_no_medals,
    x='Count',
    y='NOC',
    orientation='h',
    title='Топ 10 стран с наибольшим количеством участников без медалей на Летних Олимпийских играх',
    labels={'NOC': 'Страна', 'Count': 'Количество участников без медалей'},
    color='Count',
    color_continuous_scale='Blues'
)

fig.show()

**Выводы:**
В ходе выполнения данной лабораторной работы я познакомился с библиотеками numpy, pandas и plotly для анализа данных. Особо оценил перелесть команды groupby и мне очень зашли возможности plotly.